var keycloak = function() {}
keycloak.init = function(initOptions) {}
keycloak.login = function(options) {}
keycloak.logout = function(options) {}
keycloak.createLoginUrl= function(options) {}
keycloak.createLogoutUrl= function(options) {}
keycloak.isTokenExpired = function(minValidity) {}
keycloak.updateToken = function(minValidity) {}
keycloak.clearToken = function() {}
keycloak.loadUserProfile = function() {}
keycloak.loadUserInfo = function() {}
