#!/bin/bash

aws ecr get-login-password \
  --region us-east-1 | \
docker login \
  --username AWS \
  --password-stdin 758589815425.dkr.ecr.us-east-1.amazonaws.com
docker tag andrewslai:latest 758589815425.dkr.ecr.us-east-1.amazonaws.com/andrewslai_ecr
docker push 758589815425.dkr.ecr.us-east-1.amazonaws.com/andrewslai_ecr
